obj-m := xv6fs.o
xv6fs-objs := src/module.o xv6fs.rust.o

EXTRA_LDFLAGS += --gc-sections --entry=init_module --undefined=cleanup_module

KBUILD_EXTRA_SYMBOLS = $(src)/../../../bentofs/Module.symvers

CARGO ?= cargo

export c_flags

$(src)/target/x86_64-unknown-none-linuxkernel/release/libxv6fs.a: cargo_will_determine_dependencies
	cd $(src); env -u MAKE -u MAKEFLAGS $(CARGO) build -Z build-std=core,alloc --release --target=x86_64-unknown-none-linuxkernel

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/x86_64-unknown-none-linuxkernel/release/lib%.a
	$(LD) -r -o $@ --whole-archive $<
