obj-m := hello_ll2.o
hello_ll2-objs := src/module.o hello_ll2.rust.o

EXTRA_LDFLAGS += --gc-sections --entry=init_module --undefined=cleanup_module

KBUILD_EXTRA_SYMBOLS = $(src)/../../../bentofs/Module.symvers

CARGO ?= cargo

$(src)/target/x86_64-linux-kernel/release/libhello_ll2.a: $(src)/Cargo.toml $(wildcard $(src)/src/*.rs)
	cd $(src); env -u MAKE -u MAKEFLAGS $(CARGO) build -Z build-std=core,alloc --release --target=x86_64-linux-kernel

%.rust.o: target/x86_64-linux-kernel/release/lib%.a
	$(LD) -r -o $@ --whole-archive $<
