obj-m := xv6fs_prov.o
xv6fs_prov-objs := src/module.o xv6fs_prov.rust.o

EXTRA_LDFLAGS += --gc-sections --entry=init_module --undefined=cleanup_module

KBUILD_EXTRA_SYMBOLS = $(src)/../../../bentofs/Module.symvers

CARGO ?= cargo

export c_flags

$(src)/target/x86_64-linux-kernel/release/libxv6fs_prov.a: cargo_will_determine_dependencies
	cd $(src); env -u MAKE -u MAKEFLAGS $(CARGO) build -Z build-std=core,alloc --release --target=x86_64-linux-kernel

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/x86_64-linux-kernel/release/lib%.a
	$(LD) -r -o $@ --whole-archive $<
